#!/bin/bash

dim_help() {
    echo "Usage: $0 <command>"
    echo "Available commands:"
    command -v column >/dev/null 2>&1 && cmd="column -t -s -" || cmd=cat
    $cmd <<<'
  help - Show this help page.
  update - Update the submodules and apply the NMS patches.
  patches - Rebuild the NMS patches.
  init - Copy direct & indirect into mcp and setup Solar.
  export - Export the obfuscated code to put into a jar.'
}

dim_export(){
    #Recompile NMS
    mcp/recompile.sh

    #Reobfuscate NMS
    mcp/reobfuscate.sh	

    echo Grab the files in mcp/reobf/minecraft_server/ and put them into any vanilla jar!
}

dim_init(){
    #Copy NMS source just in case
    mkdir -p mcp/src/old_nms
    cp -a mcp/src/minecraft_server/net/ mcp/src/old_nms/net/

    echo Done copying NMS source

    #Set up Solar submodule
    cd Solar
    git submodule init
    git submodule update
    cd ..

    echo Solar set up

    #Copy Solar API into NMS
    cp -a Solar/src/dimensions mcp/src/minecraft_server/

    echo Done moving Solar code into NMS

    #Copy indirect code into NMS
    mkdir -p indirect/dimensions
    cp -a indirect/dimensions/ mcp/src/minecraft_server/

    echo Done moving indirect code into NMS
    
    cd mcp/src/minecraft_server/net/
    git init
    git checkout -b dimensions
    cd ../../../../
    
    echo Done initializing NMS

    dim_update
}

apply_patches() {
    mkdir -p mcp/src/minecraft_server/net/direct-patches/
    cp -a direct/ mcp/src/minecraft_server/net/direct-patches/
    cd mcp/src/minecraft_server/net/
    git am direct-patches
}

dim_update() {
    echo "> Updating Solar..."
    git submodule update --init
    echo "> Updating MCP..."
    apply_patches
}

make_patches() {
    cd mcp/src/minecraft_server/net/
    git format-patch -o direct-patches master
    cd ../../../../
    cp -a mcp/src/minecraft_server/net/direct-patches/ direct/
    rm -rf mcp/src/minecraft_server/net/direct-patches/
}

dim_patches() {
    echo "> Recreating patches for MCP..."
    make_patches 
}

dim_build(){
    #Run when you want to get your code ready to commit

    mkdir -p indirect/dimensions/solar

    #Copy indirect files from NMS into indirect/
    cp -a mcp/src/minecraft_server/dimensions/ indirect/

    echo Indirect code moved into indirect folder

    #Copy Solar code into Solar
    cp -a indirect/dimensions/solar/ Solar/src/dimensions/
    #Remove everything from old solar folder
    rm -rf indirect/dimensions/solar/

    echo Solar code moved into Solar/src/dimensions/solar/
    
    #Build patches into direct/
    dim_patches
}

dim_setup_eclipse(){
    mkdir -p mcp/eclipse/Server/src
    cp -a mcp/src/minecraft_server/net mcp/eclipse/Server/src
    cp -a mcp/src/minecraft_server/dimensions mcp/eclipse/Server/src
    cp -a mcp/jars mcp/eclipse/Server

    echo Files moved into eclipse/Server/
}

if [ -z $1 ]; then
    dim_help
    exit
fi

# TODO: Improve this, just a little bit lazy right now
if [ "$(type -t "dim_$1")" = "function" ]; then
    "dim_$@"
elif [ "$(type -t "dim_$1_$2")" = "function" ]; then
    "dim_$1_$2"
else
    >&2 echo "Unknown command: '$@'. Type '$0 help' for more information."
    exit 1
fi
